/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package whispir_library;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public String newGreetings() {
        return "Hello Whispir";
    }

    public String greetingsWithProps(String text) {
        return text;
    }
}
